config:
  has_zed: true
  has_usb_camera: false
  has_arm: false

servo_hat:
  i2c_bus: 7
  i2c_address: 0x40

rocker_bogie:
  channels: [0, 15, 1, 14]
  sun_position: [130, 50, 120, 60]
  regular_position: [90, 90, 60, 120]

drivetrain:
  motors:
    left:
      channel: 3
    right:
      channel: 12

usb_camera:
  pan:
    channel: 6
    min_angle: 0
    max_angle: 180
  tilt:
    channel: 7
    min_angle: 0
    max_angle: 180

zed_server:
  resolution: HD720
  fps: 30
  jpeg_quality: 80
  area_memory: false
  pose_stream_hz: 10

