rovers:
  - name: rover0
    host: rover0
    control_port: 8002
    camera_port: 8001
    ssh_username: rover

  - name: rover1
    host: rover1
    control_port: 8002
    camera_port: 8001
    ssh_username: rover
